import { BsGear, BsHouseDoor, BsKanban, BsListUl, BsPostage } from "react-icons/bs";
import { SideNavItem } from "@/../types/types";

export const SIDENAV_ITEMS:SideNavItem[] = [
    {
        title:"Dashboard",
        path:"/",
        icon: <BsHouseDoor size={20}/>
    },
    {
        title: 'Staffs',
        path: '/staffs',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Staff', path: '/products/auction'},
            {title: 'Staff Roles', path: '/products/new/auction'},
        ],
    },
    {
        title:"POS",
        path:"/pos",
        icon: <BsPostage size={20}/>
    },
    {
        title: 'Products',
        path: '/products',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All', path: '/products'},
            {title: 'Add New', path: '/products/new'},
            {title: 'In House', path: '/products/admin'},
            {title: 'Digital', path: '/products/digital'},
            {title: 'Seller', path: '/products/seller',
            submenu: true,
            subMenuItems: [
                {title: 'Physical', path: '/products/seller/physical'},
                {title: 'Digital', path: '/products/seller/digital'},
            ]},
            {title: 'Bulk Import', path: '/products/import'},
            {title: 'Bulk Export', path: '/products/Export'},
            {title: 'Category', path: '/products/category'},
            {title: 'Category Wise Discount', path: '/products/category/discount'},
            {title: 'Brands', path: '/products/brands'},
            {title: 'Attribute', path: '/products/attribute'},
            {title: 'Color', path: '/products/color'},
            {title: 'Size Guide', path: '/products/size',
            submenu: true,
            subMenuItems: [
                {title: 'Size Chart', path: '/products/size/guide'},
                {title: 'Digital', path: '/products/size/points'},
            ]},
            {title: 'Product Reviews', path: '/products/review'},
        ],
    },
    {
        title: 'Auction Products',
        path: '/products',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Auction', path: '/products/auction'},
            {title: 'Add New', path: '/products/new/auction'},
            {title: 'Admin Products', path: '/products/admin/auction'},
            {title: 'Seller Auction', path: '/products/seller/auction'},
            {title: 'Auction Orders', path: '/products/auction/order'},
        ],
    },
    {
        title: 'WholeSale Products',
        path: '/wholesale/products',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All wholesale', path: '/products/wholesale'},
            {title: 'Add New', path: '/products/new/wholesale'},
            {title: 'In House', path: '/products/admin/wholesale'},
            {title: 'Seller wholesale', path: '/products/seller/wholesale'},
        ],
    },
    {
        title: 'Sales',
        path: '/sale',
        icon: <BsListUl size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Order', path: '/products/order'},
            {title: 'In House', path: '/products/admin/order'},
            {title: 'Seller Order', path: '/products/seller/order'},
            {title: 'Pick-up Point', path: '/products/seller/pickup'},
        ],
    },
    {
        title: 'Delivery Boy',
        path: '/deliveryboy',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Delivery Boy', path: '/products/order'},
            {title: 'Payment Histories', path: '/products/admin/order'},
            {title: 'Collected Histories', path: '/products/seller/order'},
            {title: 'Cancel Request', path: '/products/seller/pickup'},
            {title: 'Configuration', path: '/products/seller/pickup'},
        ],
    },
    {
        title: 'Refunds',
        path: '/refunds',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Refund Requests', path: '/products/order'},
            {title: 'Approved Refunds', path: '/products/admin/order'},
            {title: 'Rejected Refunds', path: '/products/admin/order'},
            {title: 'Refund Configuration', path: '/products/admin/order'},
        ],
    },
    {
        title: 'Customers',
        path: '/customer',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Customer', path: '/products/order'},
            {title: 'Classified Products', path: '/products/order'},
            {title: 'Classified Packages', path: '/products/order'},
        ],
    },
    {
        title: 'Sellers',
        path: '/seller',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Seller', path: '/products/order'},
            {title: 'Payouts', path: '/products/order'},
            {title: 'Payout Requests', path: '/products/order'},
            {title: 'Seller Commission', path: '/products/order'},
            {title: 'Seller Packages', path: '/products/order'},
        ],
    },
    {
        title: 'Uploaded Files',
        path: '/upload',
        icon: <BsGear size={20} />
    },
    {
        title: 'Reports',
        path: '/report',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Admin Sale', path: '/products/order'},
            {title: 'Seller Sale', path: '/products/order'},
            {title: 'Stock', path: '/products/order'},
            {title: 'Favorite List', path: '/products/order'},
            {title: 'Visitor Searches', path: '/products/order'},
            {title: 'Commission Histories', path: '/products/order'},
            {title: 'Wallet Histories', path: '/products/order'},
        ],
    },
    {
        title: 'Blogs',
        path: '/blog',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'All Blogs', path: '/products/order'},
            {title: 'Categories', path: '/products/order'},
        ],
    },
    {
        title: 'Marketing',
        path: '/marketing',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Flash Deals', path: '/products/order'},
            {title: 'Dynamic Pop-up', path: '/products/order'},
            {title: 'Custom Alert', path: '/products/order'},
            {title: 'Newsletters', path: '/products/order'},
            {title: 'Bulk SMS', path: '/products/order'},
            {title: 'Subscribers', path: '/products/order'},
            {title: 'Coupon', path: '/products/order'},
        ],
    },
    {
        title: 'Support',
        path: '/support',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Ticket', path: '/products/order'},
            {title: 'Product Conversions', path: '/products/order'},
            {title: 'Product Queries', path: '/products/order'},
        ],
    },
    {
        title: 'Affiliate',
        path: '/affiliate',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Configarations', path: '/products/order'},
            {title: 'Affiliate Users', path: '/products/order'},
            {title: 'Referral Users', path: '/products/order'},
            {title: 'Withdraw Requests', path: '/products/order'},
            {title: 'Logs', path: '/products/order'},
        ],
    },
    {
        title: 'Offline Payment',
        path: '/offline_payment',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Manual Payment Methods', path: '/products/order'},
            {title: 'Offline Wallet Recharge', path: '/products/order'},
            {title: 'Offline Customer Package Payments', path: '/products/order'},
            {title: 'Offline Seller Package Payments', path: '/products/order'},
        ],
    },
    {
        title: 'Club Point',
        path: '/club_point',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Configurations', path: '/products/order'},
            {title: 'Product Point', path: '/products/order'},
            {title: 'User Point', path: '/products/order'},
        ],
    },
    {
        title: 'OTP',
        path: '/otp',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Configurations', path: '/products/order'},
            {title: 'SMS Templates', path: '/products/order'},
            {title: 'OTP Credentials', path: '/products/order'},
        ],
    },
    {
        title: 'Website Settings',
        path: '/setting',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Header', path: '/products/order'},
            {title: 'Footer', path: '/products/order'},
            {title: 'Pages', path: '/products/order'},
            {title: 'Appearance', path: '/products/order'},
        ],
    },
    {
        title: 'Feature Settings',
        path: '/configuration',
        icon: <BsGear size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Features Activation', path: '/products/order'},
            {title: 'Languages', path: '/products/order'},
            {title: 'Currency', path: '/products/order'},
            {title: 'VAT & TAX', path: '/products/order'},
            {title: 'Pickup Point', path: '/products/order'},
            {title: 'SMTP', path: '/products/order'},
            {title: 'Payment Methods', path: '/products/order'},
            {title: 'Order Configuration', path: '/products/order'},
            {title: 'File System', path: '/products/order'},
            {title: 'Cache Manage', path: '/products/order'},
            {title: 'Social Media Logins', path: '/products/order'},
            {title: 'Facebook', path: '/facebook',
            submenu: true,
            subMenuItems: [
                {title: 'Chat', path: '/facebook/chat'},
                {title: 'Comment', path: '/facebook/comment'},
            ]},
            {title: 'Google', path: '/google',
            submenu: true,
            subMenuItems: [
                {title: 'Analytics', path: '/google/analytics'},
                {title: 'reCaptcha', path: '/google/reCaptcha'},
                {title: 'Map', path: '/google/map'},
                {title: 'Firebase', path: '/google/firebase'},
            ]},
            {title: 'Shipping', path: '/shipping',
            submenu: true,
            subMenuItems: [
                {title: 'Configuration', path: '/shipping'},
                {title: 'Countries', path: '/google/reCaptcha'},
                {title: 'States', path: '/google/reCaptcha'},
                {title: 'Cities', path: '/google/reCaptcha'},
                {title: 'Zones', path: '/google/reCaptcha'},
                {title: 'Courier', path: '/google/reCaptcha'},
            ]},
        ],
    },
    {
        title: 'Software System',
        path: '/setting',
        icon: <BsKanban size={20} />,
        submenu: true,
        subMenuItems: [
            {title: 'Update', path: '/products/order'},
            {title: 'Server Status', path: '/products/order'},
        ],
    },
    {
        title: 'Add Feature',
        path: '/plugin',
        icon: <BsGear size={20} />
    },
]